//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Comun.Resultado
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResultado", Namespace="http://schemas.datacontract.org/2004/07/Framework.Comun.Resultado")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaDocumento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Framework.Comun.Resultado.ResultadoExterno))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaImagen))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaHuellas))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaJson))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaContrastacion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaCertificacionJson))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaCertificacion))]
    public partial class BaseResultado : object
    {
        
        private bool EsValidoField;
        
        private string MensajeField;
        
        private string TipoMensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsValido
        {
            get
            {
                return this.EsValidoField;
            }
            set
            {
                this.EsValidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMensaje
        {
            get
            {
                return this.TipoMensajeField;
            }
            set
            {
                this.TipoMensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoExterno", Namespace="http://schemas.datacontract.org/2004/07/Framework.Comun.Resultado")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaImagen))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaHuellas))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaJson))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaContrastacion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaCertificacionJson))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaCertificacion))]
    public partial class ResultadoExterno : Framework.Comun.Resultado.BaseResultado
    {
        
        private int CodigoRespuestaField;
        
        private string CodigoUnicoField;
        
        private string DescripcionRespuestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRespuesta
        {
            get
            {
                return this.CodigoRespuestaField;
            }
            set
            {
                this.CodigoRespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoUnico
        {
            get
            {
                return this.CodigoUnicoField;
            }
            set
            {
                this.CodigoUnicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionRespuesta
        {
            get
            {
                return this.DescripcionRespuestaField;
            }
            set
            {
                this.DescripcionRespuestaField = value;
            }
        }
    }
}
namespace Convenio.Core.Modelo.Dto.Proceso.ServicioExterno
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaDocumento", Namespace="http://schemas.datacontract.org/2004/07/Convenio.Core.Modelo.Dto.Proceso.Servicio" +
        "Externo")]
    public partial class RespuestaDocumento : Framework.Comun.Resultado.BaseResultado
    {
        
        private byte[] ReporteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Reporte
        {
            get
            {
                return this.ReporteField;
            }
            set
            {
                this.ReporteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaConsultaImagen", Namespace="http://schemas.datacontract.org/2004/07/Convenio.Core.Modelo.Dto.Proceso.Servicio" +
        "Externo")]
    public partial class RespuestaConsultaImagen : Framework.Comun.Resultado.ResultadoExterno
    {
        
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen
        {
            get
            {
                return this.ImagenField;
            }
            set
            {
                this.ImagenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaConsultaHuellas", Namespace="http://schemas.datacontract.org/2004/07/Convenio.Core.Modelo.Dto.Proceso.Servicio" +
        "Externo")]
    public partial class RespuestaConsultaHuellas : Framework.Comun.Resultado.ResultadoExterno
    {
        
        private string CodigoUnicoConsultaField;
        
        private Identidad.Core.Modelo.Dto.ProcesoAplicacion.HuellaCalidadDto[] HuellasDisponiblesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoUnicoConsulta
        {
            get
            {
                return this.CodigoUnicoConsultaField;
            }
            set
            {
                this.CodigoUnicoConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Identidad.Core.Modelo.Dto.ProcesoAplicacion.HuellaCalidadDto[] HuellasDisponibles
        {
            get
            {
                return this.HuellasDisponiblesField;
            }
            set
            {
                this.HuellasDisponiblesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaConsultaJson", Namespace="http://schemas.datacontract.org/2004/07/Convenio.Core.Modelo.Dto.Proceso.Servicio" +
        "Externo")]
    public partial class RespuestaConsultaJson : Framework.Comun.Resultado.ResultadoExterno
    {
        
        private string DatosPersonaEnFormatoJsonField;
        
        private byte[] FotografiaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatosPersonaEnFormatoJson
        {
            get
            {
                return this.DatosPersonaEnFormatoJsonField;
            }
            set
            {
                this.DatosPersonaEnFormatoJsonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Fotografia
        {
            get
            {
                return this.FotografiaField;
            }
            set
            {
                this.FotografiaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaConsultaContrastacion", Namespace="http://schemas.datacontract.org/2004/07/Convenio.Core.Modelo.Dto.Proceso.Servicio" +
        "Externo")]
    public partial class RespuestaConsultaContrastacion : Framework.Comun.Resultado.ResultadoExterno
    {
        
        private string ContrastacionEnFormatoJsonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContrastacionEnFormatoJson
        {
            get
            {
                return this.ContrastacionEnFormatoJsonField;
            }
            set
            {
                this.ContrastacionEnFormatoJsonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaVerificacion", Namespace="http://schemas.datacontract.org/2004/07/Convenio.Core.Modelo.Dto.Proceso.Servicio" +
        "Externo")]
    public partial class RespuestaVerificacion : Framework.Comun.Resultado.ResultadoExterno
    {
        
        private byte[] ReporteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Reporte
        {
            get
            {
                return this.ReporteField;
            }
            set
            {
                this.ReporteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaConsultaCertificacionJson", Namespace="http://schemas.datacontract.org/2004/07/Convenio.Core.Modelo.Dto.Proceso.Servicio" +
        "Externo")]
    public partial class RespuestaConsultaCertificacionJson : Framework.Comun.Resultado.ResultadoExterno
    {
        
        private byte[] FotografiaField;
        
        private System.Nullable<long> IdDocumentoRespuestaField;
        
        private System.Nullable<long> IdDocumentoSolicitudField;
        
        private string ReporteCertificacionJsonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Fotografia
        {
            get
            {
                return this.FotografiaField;
            }
            set
            {
                this.FotografiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> IdDocumentoRespuesta
        {
            get
            {
                return this.IdDocumentoRespuestaField;
            }
            set
            {
                this.IdDocumentoRespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> IdDocumentoSolicitud
        {
            get
            {
                return this.IdDocumentoSolicitudField;
            }
            set
            {
                this.IdDocumentoSolicitudField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReporteCertificacionJson
        {
            get
            {
                return this.ReporteCertificacionJsonField;
            }
            set
            {
                this.ReporteCertificacionJsonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaConsultaCertificacion", Namespace="http://schemas.datacontract.org/2004/07/Convenio.Core.Modelo.Dto.Proceso.Servicio" +
        "Externo")]
    public partial class RespuestaConsultaCertificacion : Framework.Comun.Resultado.ResultadoExterno
    {
        
        private byte[] ReporteCertificacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ReporteCertificacion
        {
            get
            {
                return this.ReporteCertificacionField;
            }
            set
            {
                this.ReporteCertificacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoDetalleConsultaUsuarioFinal", Namespace="http://schemas.datacontract.org/2004/07/Convenio.Core.Modelo.Dto.Proceso.Servicio" +
        "Externo")]
    public partial class ResultadoDetalleConsultaUsuarioFinal : Comun.Core.Modelo.Dto.Autorizacion.Proceso.ResultadoExterno
    {
        
        private string ListaDatoConsultaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListaDatoConsulta
        {
            get
            {
                return this.ListaDatoConsultaField;
            }
            set
            {
                this.ListaDatoConsultaField = value;
            }
        }
    }
}
namespace Identidad.Core.Modelo.Dto.ProcesoAplicacion
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HuellaCalidadDto", Namespace="http://schemas.datacontract.org/2004/07/Identidad.Core.Modelo.Dto.ProcesoAplicaci" +
        "on")]
    public partial class HuellaCalidadDto : object
    {
        
        private string CalidadField;
        
        private string HuellaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calidad
        {
            get
            {
                return this.CalidadField;
            }
            set
            {
                this.CalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Huella
        {
            get
            {
                return this.HuellaField;
            }
            set
            {
                this.HuellaField = value;
            }
        }
    }
}
namespace Comun.Core.Modelo.Dto.Autorizacion.Proceso
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoExterno", Namespace="http://schemas.datacontract.org/2004/07/Comun.Core.Modelo.Dto.Autorizacion.Proces" +
        "o")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.ResultadoDetalleConsultaUsuarioFinal))]
    public partial class ResultadoExterno : object
    {
        
        private string ClaveAccesoField;
        
        private bool EsValidoField;
        
        private string MensajeField;
        
        private string TipoMensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveAcceso
        {
            get
            {
                return this.ClaveAccesoField;
            }
            set
            {
                this.ClaveAccesoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsValido
        {
            get
            {
                return this.EsValidoField;
            }
            set
            {
                this.EsValidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMensaje
        {
            get
            {
                return this.TipoMensajeField;
            }
            set
            {
                this.TipoMensajeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServicioExternoInstitucion")]
public interface IServicioExternoInstitucion
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoPersonaCertificacion", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoPersonaCertificacionRe" +
        "sponse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaCertificacion> ConsultaDatoPersonaCertificacionAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroDocumento, string pComplemento, string pNombre, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoPersonaImagen", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoPersonaImagenResponse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaImagen> ConsultaDatoPersonaImagenAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroDocumento, string pComplemento, string pNombre, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoPersonaHuellas", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoPersonaHuellasResponse" +
        "")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaHuellas> ConsultaDatoPersonaHuellasAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroDocumento, string pComplemento, string pNombre, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoPersonaEnJson", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoPersonaEnJsonResponse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaJson> ConsultaDatoPersonaEnJsonAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroDocumento, string pComplemento, string pNombre, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/ConsultaDocumentoDatoPersonaEnJson" +
        "", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/ConsultaDocumentoDatoPersonaEnJson" +
        "Response")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaJson> ConsultaDocumentoDatoPersonaEnJsonAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroDocumento, string pComplemento, string pNombre, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento, string pFechaExpiracion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoPersonaContrastacion", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoPersonaContrastacionRe" +
        "sponse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaContrastacion> ConsultaDatoPersonaContrastacionAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pListaCampo, int pTipoPersona);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoPersonaContrastacionBa" +
        "sica", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoPersonaContrastacionBa" +
        "sicaResponse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaContrastacion> ConsultaDatoPersonaContrastacionBasicaAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pListaCampo, int pNumeroLineaTelefonica, string pImeiDispositivoMovil, int pTipoPersona);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/VerificacionImagenDocumentoCi", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/VerificacionImagenDocumentoCiRespo" +
        "nse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionImagenDocumentoCiAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroDocumento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/VerificacionImagenDocumentoCie", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/VerificacionImagenDocumentoCieResp" +
        "onse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionImagenDocumentoCieAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroDocumento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/VerificacionImagenDocumentoLic", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/VerificacionImagenDocumentoLicResp" +
        "onse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionImagenDocumentoLicAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroLicencia);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/VerificacionImagenDocumentoLice", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/VerificacionImagenDocumentoLiceRes" +
        "ponse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionImagenDocumentoLiceAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroLicencia);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoDocumentoCi", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoDocumentoCiRespons" +
        "e")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoDocumentoCiAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroDocumento, string pComplemento, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoDocumentoCie", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoDocumentoCieRespon" +
        "se")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoDocumentoCieAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroDocumento, string pComplemento, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoDocumentoLic", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoDocumentoLicRespon" +
        "se")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoDocumentoLicAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroLicencia, string pCategoriaLicencia, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoDocumentoLice", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoDocumentoLiceRespo" +
        "nse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoDocumentoLiceAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroLicencia, string pCategoriaLicencia, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoImagenDocumentoCi", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoImagenDocumentoCiR" +
        "esponse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoImagenDocumentoCiAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroDocumento, string pComplemento, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoImagenDocumentoCie" +
        "", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoImagenDocumentoCie" +
        "Response")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoImagenDocumentoCieAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroDocumento, string pComplemento, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoImagenDocumentoLic" +
        "", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoImagenDocumentoLic" +
        "Response")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoImagenDocumentoLicAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroLicencia, string pCategoriaLicencia, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoImagenDocumentoLic" +
        "e", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/VerificacionDatoImagenDocumentoLic" +
        "eResponse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoImagenDocumentoLiceAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroLicencia, string pCategoriaLicencia, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/ObtenerDocumentoPorCodigoUnico", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/ObtenerDocumentoPorCodigoUnicoResp" +
        "onse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaDocumento> ObtenerDocumentoPorCodigoUnicoAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroUnicoDocumento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoPesonaConBiometriaJson" +
        "", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoPesonaConBiometriaJson" +
        "Response")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaCertificacionJson> ConsultaDatoPesonaConBiometriaJsonAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pIdentificadorPersona, byte[] pTempleta, string pFormato, string pStandar);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/ConsultaVerificacionCertificacionC" +
        "odigoQr", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/ConsultaVerificacionCertificacionC" +
        "odigoQrResponse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaCertificacion> ConsultaVerificacionCertificacionCodigoQrAsync(int pIdInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoQr);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/ConsultaVerificacionBiometricaFaci" +
        "al", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/ConsultaVerificacionBiometricaFaci" +
        "alResponse")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaCertificacion> ConsultaVerificacionBiometricaFacialAsync(int pIdInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pFotoBase, string pNumeroDocumento, string pComplemento);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoDetalleUsuario", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/ConsultaDatoDetalleUsuarioResponse" +
        "")]
    System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.ResultadoDetalleConsultaUsuarioFinal> ConsultaDatoDetalleUsuarioAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pFechaInicio, string pFechaFin);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioExternoInstitucion/ObtieneVersionSistema", ReplyAction="http://tempuri.org/IServicioExternoInstitucion/ObtieneVersionSistemaResponse")]
    System.Threading.Tasks.Task<string> ObtieneVersionSistemaAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
public interface IServicioExternoInstitucionChannel : IServicioExternoInstitucion, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
public partial class ServicioExternoInstitucionClient : System.ServiceModel.ClientBase<IServicioExternoInstitucion>, IServicioExternoInstitucion
{
    
    /// <summary>
    /// Implemente este método parcial para configurar el punto de conexión de servicio.
    /// </summary>
    /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
    /// <param name="clientCredentials">Credenciales de cliente</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public ServicioExternoInstitucionClient() : 
            base(ServicioExternoInstitucionClient.GetDefaultBinding(), ServicioExternoInstitucionClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.httpBasicConfig.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public ServicioExternoInstitucionClient(EndpointConfiguration endpointConfiguration) : 
            base(ServicioExternoInstitucionClient.GetBindingForEndpoint(endpointConfiguration), ServicioExternoInstitucionClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public ServicioExternoInstitucionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(ServicioExternoInstitucionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public ServicioExternoInstitucionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(ServicioExternoInstitucionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public ServicioExternoInstitucionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaCertificacion> ConsultaDatoPersonaCertificacionAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroDocumento, string pComplemento, string pNombre, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento)
    {
        return base.Channel.ConsultaDatoPersonaCertificacionAsync(pCodigoInstitucion, pUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pNumeroDocumento, pComplemento, pNombre, pPrimerApellido, pSegundoApellido, pFechaNacimiento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaImagen> ConsultaDatoPersonaImagenAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroDocumento, string pComplemento, string pNombre, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento)
    {
        return base.Channel.ConsultaDatoPersonaImagenAsync(pCodigoInstitucion, pUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pNumeroDocumento, pComplemento, pNombre, pPrimerApellido, pSegundoApellido, pFechaNacimiento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaHuellas> ConsultaDatoPersonaHuellasAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroDocumento, string pComplemento, string pNombre, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento)
    {
        return base.Channel.ConsultaDatoPersonaHuellasAsync(pCodigoInstitucion, pUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pNumeroDocumento, pComplemento, pNombre, pPrimerApellido, pSegundoApellido, pFechaNacimiento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaJson> ConsultaDatoPersonaEnJsonAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroDocumento, string pComplemento, string pNombre, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento)
    {
        return base.Channel.ConsultaDatoPersonaEnJsonAsync(pCodigoInstitucion, pUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pNumeroDocumento, pComplemento, pNombre, pPrimerApellido, pSegundoApellido, pFechaNacimiento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaJson> ConsultaDocumentoDatoPersonaEnJsonAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroDocumento, string pComplemento, string pNombre, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento, string pFechaExpiracion)
    {
        return base.Channel.ConsultaDocumentoDatoPersonaEnJsonAsync(pCodigoInstitucion, pUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pNumeroDocumento, pComplemento, pNombre, pPrimerApellido, pSegundoApellido, pFechaNacimiento, pFechaExpiracion);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaContrastacion> ConsultaDatoPersonaContrastacionAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pListaCampo, int pTipoPersona)
    {
        return base.Channel.ConsultaDatoPersonaContrastacionAsync(pCodigoInstitucion, pUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pListaCampo, pTipoPersona);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaContrastacion> ConsultaDatoPersonaContrastacionBasicaAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pListaCampo, int pNumeroLineaTelefonica, string pImeiDispositivoMovil, int pTipoPersona)
    {
        return base.Channel.ConsultaDatoPersonaContrastacionBasicaAsync(pCodigoInstitucion, pUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pListaCampo, pNumeroLineaTelefonica, pImeiDispositivoMovil, pTipoPersona);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionImagenDocumentoCiAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroDocumento)
    {
        return base.Channel.VerificacionImagenDocumentoCiAsync(pCodigoInstitucion, pNombreUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pCodigoUnico, pNumeroDocumento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionImagenDocumentoCieAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroDocumento)
    {
        return base.Channel.VerificacionImagenDocumentoCieAsync(pCodigoInstitucion, pNombreUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pCodigoUnico, pNumeroDocumento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionImagenDocumentoLicAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroLicencia)
    {
        return base.Channel.VerificacionImagenDocumentoLicAsync(pCodigoInstitucion, pNombreUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pCodigoUnico, pNumeroLicencia);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionImagenDocumentoLiceAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroLicencia)
    {
        return base.Channel.VerificacionImagenDocumentoLiceAsync(pCodigoInstitucion, pNombreUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pCodigoUnico, pNumeroLicencia);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoDocumentoCiAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroDocumento, string pComplemento, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento)
    {
        return base.Channel.VerificacionDatoDocumentoCiAsync(pCodigoInstitucion, pNombreUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pNumeroDocumento, pComplemento, pNombres, pPrimerApellido, pSegundoApellido, pFechaNacimiento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoDocumentoCieAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroDocumento, string pComplemento, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento)
    {
        return base.Channel.VerificacionDatoDocumentoCieAsync(pCodigoInstitucion, pNombreUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pNumeroDocumento, pComplemento, pNombres, pPrimerApellido, pSegundoApellido, pFechaNacimiento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoDocumentoLicAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroLicencia, string pCategoriaLicencia, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento)
    {
        return base.Channel.VerificacionDatoDocumentoLicAsync(pCodigoInstitucion, pNombreUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pNumeroLicencia, pCategoriaLicencia, pNombres, pPrimerApellido, pSegundoApellido, pFechaNacimiento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoDocumentoLiceAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pNumeroLicencia, string pCategoriaLicencia, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento)
    {
        return base.Channel.VerificacionDatoDocumentoLiceAsync(pCodigoInstitucion, pNombreUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pNumeroLicencia, pCategoriaLicencia, pNombres, pPrimerApellido, pSegundoApellido, pFechaNacimiento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoImagenDocumentoCiAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroDocumento, string pComplemento, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento)
    {
        return base.Channel.VerificacionDatoImagenDocumentoCiAsync(pCodigoInstitucion, pNombreUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pCodigoUnico, pNumeroDocumento, pComplemento, pNombres, pPrimerApellido, pSegundoApellido, pFechaNacimiento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoImagenDocumentoCieAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroDocumento, string pComplemento, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento)
    {
        return base.Channel.VerificacionDatoImagenDocumentoCieAsync(pCodigoInstitucion, pNombreUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pCodigoUnico, pNumeroDocumento, pComplemento, pNombres, pPrimerApellido, pSegundoApellido, pFechaNacimiento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoImagenDocumentoLicAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroLicencia, string pCategoriaLicencia, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento)
    {
        return base.Channel.VerificacionDatoImagenDocumentoLicAsync(pCodigoInstitucion, pNombreUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pCodigoUnico, pNumeroLicencia, pCategoriaLicencia, pNombres, pPrimerApellido, pSegundoApellido, pFechaNacimiento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaVerificacion> VerificacionDatoImagenDocumentoLiceAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoUnico, string pNumeroLicencia, string pCategoriaLicencia, string pNombres, string pPrimerApellido, string pSegundoApellido, string pFechaNacimiento)
    {
        return base.Channel.VerificacionDatoImagenDocumentoLiceAsync(pCodigoInstitucion, pNombreUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pCodigoUnico, pNumeroLicencia, pCategoriaLicencia, pNombres, pPrimerApellido, pSegundoApellido, pFechaNacimiento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaDocumento> ObtenerDocumentoPorCodigoUnicoAsync(int pCodigoInstitucion, string pNombreUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroUnicoDocumento)
    {
        return base.Channel.ObtenerDocumentoPorCodigoUnicoAsync(pCodigoInstitucion, pNombreUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroUnicoDocumento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaCertificacionJson> ConsultaDatoPesonaConBiometriaJsonAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pIdentificadorPersona, byte[] pTempleta, string pFormato, string pStandar)
    {
        return base.Channel.ConsultaDatoPesonaConBiometriaJsonAsync(pCodigoInstitucion, pUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pIdentificadorPersona, pTempleta, pFormato, pStandar);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaCertificacion> ConsultaVerificacionCertificacionCodigoQrAsync(int pIdInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pCodigoQr)
    {
        return base.Channel.ConsultaVerificacionCertificacionCodigoQrAsync(pIdInstitucion, pUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pCodigoQr);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.RespuestaConsultaCertificacion> ConsultaVerificacionBiometricaFacialAsync(int pIdInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pFotoBase, string pNumeroDocumento, string pComplemento)
    {
        return base.Channel.ConsultaVerificacionBiometricaFacialAsync(pIdInstitucion, pUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pFotoBase, pNumeroDocumento, pComplemento);
    }
    
    public System.Threading.Tasks.Task<Convenio.Core.Modelo.Dto.Proceso.ServicioExterno.ResultadoDetalleConsultaUsuarioFinal> ConsultaDatoDetalleUsuarioAsync(int pCodigoInstitucion, string pUsuario, string pContrasenia, string pClaveAccesoUsuarioFinal, string pNumeroAutorizacion, string pFechaInicio, string pFechaFin)
    {
        return base.Channel.ConsultaDatoDetalleUsuarioAsync(pCodigoInstitucion, pUsuario, pContrasenia, pClaveAccesoUsuarioFinal, pNumeroAutorizacion, pFechaInicio, pFechaFin);
    }
    
    public System.Threading.Tasks.Task<string> ObtieneVersionSistemaAsync()
    {
        return base.Channel.ObtieneVersionSistemaAsync();
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.httpBasicConfig))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.httpBasicConfig))
        {
            return new System.ServiceModel.EndpointAddress("http://testconsultarui.segip.gob.bo/ServicioExternoInstitucion.svc");
        }
        throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return ServicioExternoInstitucionClient.GetBindingForEndpoint(EndpointConfiguration.httpBasicConfig);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return ServicioExternoInstitucionClient.GetEndpointAddress(EndpointConfiguration.httpBasicConfig);
    }
    
    public enum EndpointConfiguration
    {
        
        httpBasicConfig,
    }
}
